# Generated by Django 3.0.4 on 2020-05-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('value', models.CharField(max_length=100, verbose_name='Wert')),
            ],
        ),
    ]
