# Generated by Django 3.0.4 on 2020-05-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinevars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={'verbose_name': 'Variable', 'verbose_name_plural': 'Variablen'},
        ),
        migrations.AlterField(
            model_name='variable',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Wert'),
        ),
    ]
