# Generated by Django 3.0.4 on 2020-06-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinevars', '0002_auto_20200521_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='value',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Wert'),
        ),
    ]
